version: '3'

services:
  nginx:
    image: dgurney/corona-window-nginx:latest
    depends_on:
      - api
    restart: always
    ports:
      - 80:80
      - 443:443
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - DOMAIN=api-staging.coronawindow.com

  api:
    image: dgurney/corona-window-api:latest
    depends_on:
      - redis
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=corona-window-staging.ctgvfpoeqoab.us-east-1.rds.amazonaws.com
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RTMP_ORIGIN=rtmp://api-staging.coronawindow.com:1935
      - RTMP_PATH=/stream
      - WEB_ORIGIN=https://staging.coronawindow.com
      - COOKIE_SESSION_KEY=${COOKIE_SESSION_KEY}
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_S3_BUCKET=corona-window-dev
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}

  redis:
    image: redis:alpine
    restart: always

  rtmp:
    image: dgurney/corona-window-rtmp:latest
    restart: always
    ports:
      - 1935:1935
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
      - API_RTMP_EVENT_URL=http://api:4000/rtmp-event
    volumes:
      - ./certs:/opt/certs
