version: '3'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

  rtmp:
    build: ./rtmp
    restart: always
    ports:
      - 1935:1935
    environment:
      - HTTP_PORT=80
      - RTMP_PORT=1935
      - API_RTMP_EVENT_URL=http://localhost:4000/rtmp-event
    volumes:
      - ./certs:/opt/certs

  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
