import { User } from 'entities/User';

export const buildCreateChannelParams = (user: User) => ({
  ChannelClass: 'SINGLE_PIPELINE',
  Destinations: [
    {
      Id: 'destination1',
      MediaPackageSettings: [],
      Settings: [
        {
          Url: user.awsMediaPackageChannelIngestUrl,
          Username: user.awsMediaPackageChannelIngestUsername,
          PasswordParam: user.awsMediaPackageChannelIngestPasswordParam,
        },
      ],
    },
  ],
  EncoderSettings: {
    AudioDescriptions: [
      {
        AudioSelectorName: 'default',
        AudioTypeControl: 'FOLLOW_INPUT',
        CodecSettings: {
          AacSettings: {
            Bitrate: 64000,
            RawFormat: 'NONE',
            Spec: 'MPEG4',
          },
        },
        LanguageCodeControl: 'FOLLOW_INPUT',
        Name: 'audio_1_aac64',
      },
      {
        AudioSelectorName: 'default',
        AudioTypeControl: 'FOLLOW_INPUT',
        CodecSettings: {
          AacSettings: {
            Bitrate: 64000,
            RawFormat: 'NONE',
            Spec: 'MPEG4',
          },
        },
        LanguageCodeControl: 'FOLLOW_INPUT',
        Name: 'audio_2_aac64',
      },
      {
        AudioSelectorName: 'default',
        AudioTypeControl: 'FOLLOW_INPUT',
        CodecSettings: {
          AacSettings: {
            Bitrate: 64000,
            RawFormat: 'NONE',
            Spec: 'MPEG4',
          },
        },
        LanguageCodeControl: 'FOLLOW_INPUT',
        Name: 'audio_3_aac64',
      },
      {
        AudioSelectorName: 'default',
        AudioTypeControl: 'FOLLOW_INPUT',
        CodecSettings: {
          AacSettings: {
            Bitrate: 96000,
            RawFormat: 'NONE',
            Spec: 'MPEG4',
          },
        },
        LanguageCodeControl: 'FOLLOW_INPUT',
        Name: 'audio_1_aac96',
      },
      {
        AudioSelectorName: 'default',
        AudioTypeControl: 'FOLLOW_INPUT',
        CodecSettings: {
          AacSettings: {
            Bitrate: 96000,
            RawFormat: 'NONE',
            Spec: 'MPEG4',
          },
        },
        LanguageCodeControl: 'FOLLOW_INPUT',
        Name: 'audio_2_aac96',
      },
      {
        AudioSelectorName: 'default',
        AudioTypeControl: 'FOLLOW_INPUT',
        CodecSettings: {
          AacSettings: {
            Bitrate: 96000,
            RawFormat: 'NONE',
            Spec: 'MPEG4',
          },
        },
        LanguageCodeControl: 'FOLLOW_INPUT',
        Name: 'audio_3_aac96',
      },
    ],
    CaptionDescriptions: [],
    OutputGroups: [
      {
        Name: 'TN2224',
        OutputGroupSettings: {
          HlsGroupSettings: {
            AdMarkers: [],
            CaptionLanguageMappings: [],
            CaptionLanguageSetting: 'OMIT',
            ClientCache: 'DISABLED',
            CodecSpecification: 'RFC_4281',
            Destination: {
              DestinationRefId: 'destination1',
            },
            DirectoryStructure: 'SINGLE_DIRECTORY',
            HlsCdnSettings: {
              HlsBasicPutSettings: {
                ConnectionRetryInterval: 1,
                FilecacheDuration: 300,
                NumRetries: 10,
                RestartDelay: 5,
              },
            },
            HlsId3SegmentTagging: 'DISABLED',
            IFrameOnlyPlaylists: 'DISABLED',
            IndexNSegments: 4,
            InputLossAction: 'EMIT_OUTPUT',
            IvInManifest: 'INCLUDE',
            IvSource: 'FOLLOWS_SEGMENT_NUMBER',
            KeepSegments: 12,
            ManifestCompression: 'NONE',
            ManifestDurationFormat: 'FLOATING_POINT',
            Mode: 'LIVE',
            OutputSelection: 'MANIFESTS_AND_SEGMENTS',
            ProgramDateTime: 'INCLUDE',
            ProgramDateTimePeriod: 600,
            RedundantManifest: 'DISABLED',
            SegmentLength: 2,
            SegmentationMode: 'USE_SEGMENT_DURATION',
            SegmentsPerSubdirectory: 10000,
            StreamInfResolution: 'INCLUDE',
            TimedMetadataId3Frame: 'PRIV',
            TimedMetadataId3Period: 10,
            TsFileMode: 'SEGMENTED_FILES',
          },
        },
        Outputs: [
          {
            AudioDescriptionNames: ['audio_2_aac96'],
            CaptionDescriptionNames: [],
            OutputSettings: {
              HlsOutputSettings: {
                H265PackagingType: 'HVC1',
                HlsSettings: {
                  StandardHlsSettings: {
                    AudioRenditionSets: 'program_audio',
                    M3u8Settings: {
                      AudioFramesPerPes: 4,
                      AudioPids: '492-498',
                      EcmPid: '8182',
                      NielsenId3Behavior: 'NO_PASSTHROUGH',
                      PcrControl: 'PCR_EVERY_PES_PACKET',
                      PmtPid: '480',
                      ProgramNum: 1,
                      Scte35Behavior: 'NO_PASSTHROUGH',
                      Scte35Pid: '500',
                      TimedMetadataBehavior: 'NO_PASSTHROUGH',
                      TimedMetadataPid: '502',
                      VideoPid: '481',
                    },
                  },
                },
                NameModifier: '_960x540_2000k',
              },
            },
            VideoDescriptionName: 'video_960_540',
          },
          {
            AudioDescriptionNames: ['audio_3_aac96'],
            CaptionDescriptionNames: [],
            OutputSettings: {
              HlsOutputSettings: {
                HlsSettings: {
                  StandardHlsSettings: {
                    AudioRenditionSets: 'program_audio',
                    M3u8Settings: {
                      AudioPids: '492-498',
                      EcmPid: '8182',
                      PcrControl: 'PCR_EVERY_PES_PACKET',
                      PmtPid: '480',
                      Scte35Behavior: 'NO_PASSTHROUGH',
                      Scte35Pid: '500',
                      TimedMetadataBehavior: 'NO_PASSTHROUGH',
                      TimedMetadataPid: '502',
                      VideoPid: '481',
                    },
                  },
                },
                NameModifier: '_1280x720_3300k',
              },
            },
            VideoDescriptionName: 'video_1280_720_1',
          },
          {
            AudioDescriptionNames: ['audio_1_aac64'],
            CaptionDescriptionNames: [],
            OutputSettings: {
              HlsOutputSettings: {
                HlsSettings: {
                  StandardHlsSettings: {
                    AudioRenditionSets: 'program_audio',
                    M3u8Settings: {
                      AudioPids: '492-498',
                      EcmPid: '8182',
                      PcrControl: 'PCR_EVERY_PES_PACKET',
                      PmtPid: '480',
                      Scte35Behavior: 'NO_PASSTHROUGH',
                      Scte35Pid: '500',
                      TimedMetadataBehavior: 'NO_PASSTHROUGH',
                      TimedMetadataPid: '502',
                      VideoPid: '481',
                    },
                  },
                },
                NameModifier: '_416x234_200k',
              },
            },
            VideoDescriptionName: 'video_416_234',
          },
          {
            AudioDescriptionNames: ['audio_2_aac64'],
            CaptionDescriptionNames: [],
            OutputSettings: {
              HlsOutputSettings: {
                HlsSettings: {
                  StandardHlsSettings: {
                    AudioRenditionSets: 'program_audio',
                    M3u8Settings: {
                      AudioPids: '492-498',
                      EcmPid: '8182',
                      PcrControl: 'PCR_EVERY_PES_PACKET',
                      PmtPid: '480',
                      Scte35Behavior: 'NO_PASSTHROUGH',
                      Scte35Pid: '500',
                      TimedMetadataBehavior: 'NO_PASSTHROUGH',
                      TimedMetadataPid: '502',
                      VideoPid: '481',
                    },
                  },
                },
                NameModifier: '_480x270_400k',
              },
            },
            VideoDescriptionName: 'video_480_270',
          },
          {
            AudioDescriptionNames: ['audio_3_aac64'],
            CaptionDescriptionNames: [],
            OutputSettings: {
              HlsOutputSettings: {
                HlsSettings: {
                  StandardHlsSettings: {
                    AudioRenditionSets: 'program_audio',
                    M3u8Settings: {
                      AudioPids: '492-498',
                      EcmPid: '8182',
                      PcrControl: 'PCR_EVERY_PES_PACKET',
                      PmtPid: '480',
                      Scte35Behavior: 'NO_PASSTHROUGH',
                      Scte35Pid: '500',
                      TimedMetadataBehavior: 'NO_PASSTHROUGH',
                      TimedMetadataPid: '502',
                      VideoPid: '481',
                    },
                  },
                },
                NameModifier: '_640x360_800k',
              },
            },
            VideoDescriptionName: 'video_640_360',
          },
          {
            AudioDescriptionNames: ['audio_1_aac96'],
            CaptionDescriptionNames: [],
            OutputSettings: {
              HlsOutputSettings: {
                HlsSettings: {
                  StandardHlsSettings: {
                    AudioRenditionSets: 'program_audio',
                    M3u8Settings: {
                      AudioPids: '492-498',
                      EcmPid: '8182',
                      PcrControl: 'PCR_EVERY_PES_PACKET',
                      PmtPid: '480',
                      Scte35Behavior: 'NO_PASSTHROUGH',
                      Scte35Pid: '500',
                      TimedMetadataBehavior: 'NO_PASSTHROUGH',
                      TimedMetadataPid: '502',
                      VideoPid: '481',
                    },
                  },
                },
                NameModifier: '_768x432_1200k',
              },
            },
            VideoDescriptionName: 'video_768_432',
          },
        ],
      },
    ],
    TimecodeConfig: {
      Source: 'SYSTEMCLOCK',
    },
    VideoDescriptions: [
      {
        CodecSettings: {
          H264Settings: {
            AdaptiveQuantization: 'HIGH',
            Bitrate: 200000,
            ColorMetadata: 'INSERT',
            EntropyEncoding: 'CAVLC',
            FlickerAq: 'ENABLED',
            FramerateControl: 'SPECIFIED',
            FramerateDenominator: 1001,
            FramerateNumerator: 15000,
            GopBReference: 'DISABLED',
            GopNumBFrames: 0,
            GopSize: 30,
            GopSizeUnits: 'FRAMES',
            Level: 'H264_LEVEL_3',
            LookAheadRateControl: 'HIGH',
            ParControl: 'INITIALIZE_FROM_SOURCE',
            Profile: 'BASELINE',
            RateControlMode: 'CBR',
            SceneChangeDetect: 'ENABLED',
            SpatialAq: 'ENABLED',
            Syntax: 'DEFAULT',
            TemporalAq: 'ENABLED',
          },
        },
        Height: 236,
        Name: 'video_416_234',
        ScalingBehavior: 'DEFAULT',
        Width: 416,
      },
      {
        CodecSettings: {
          H264Settings: {
            AdaptiveQuantization: 'HIGH',
            Bitrate: 400000,
            ColorMetadata: 'INSERT',
            EntropyEncoding: 'CAVLC',
            FlickerAq: 'ENABLED',
            FramerateControl: 'SPECIFIED',
            FramerateDenominator: 1001,
            FramerateNumerator: 15000,
            GopBReference: 'DISABLED',
            GopNumBFrames: 0,
            GopSize: 30,
            GopSizeUnits: 'FRAMES',
            Level: 'H264_LEVEL_3',
            LookAheadRateControl: 'HIGH',
            ParControl: 'INITIALIZE_FROM_SOURCE',
            Profile: 'BASELINE',
            RateControlMode: 'CBR',
            SceneChangeDetect: 'ENABLED',
            SpatialAq: 'ENABLED',
            Syntax: 'DEFAULT',
            TemporalAq: 'ENABLED',
          },
        },
        Height: 272,
        Name: 'video_480_270',
        ScalingBehavior: 'DEFAULT',
        Width: 480,
      },
      {
        CodecSettings: {
          H264Settings: {
            AdaptiveQuantization: 'HIGH',
            Bitrate: 800000,
            ColorMetadata: 'INSERT',
            EntropyEncoding: 'CABAC',
            FlickerAq: 'ENABLED',
            FramerateControl: 'SPECIFIED',
            FramerateDenominator: 1001,
            FramerateNumerator: 30000,
            GopBReference: 'ENABLED',
            GopNumBFrames: 3,
            GopSize: 60,
            GopSizeUnits: 'FRAMES',
            Level: 'H264_LEVEL_3',
            LookAheadRateControl: 'HIGH',
            ParControl: 'INITIALIZE_FROM_SOURCE',
            Profile: 'MAIN',
            RateControlMode: 'CBR',
            SceneChangeDetect: 'ENABLED',
            SpatialAq: 'ENABLED',
            Syntax: 'DEFAULT',
            TemporalAq: 'ENABLED',
          },
        },
        Height: 360,
        Name: 'video_640_360',
        ScalingBehavior: 'DEFAULT',
        Width: 640,
      },
      {
        CodecSettings: {
          H264Settings: {
            AdaptiveQuantization: 'HIGH',
            Bitrate: 1200000,
            ColorMetadata: 'INSERT',
            EntropyEncoding: 'CABAC',
            FlickerAq: 'ENABLED',
            FramerateControl: 'SPECIFIED',
            FramerateDenominator: 1001,
            FramerateNumerator: 30000,
            GopBReference: 'ENABLED',
            GopNumBFrames: 3,
            GopSize: 60,
            GopSizeUnits: 'FRAMES',
            Level: 'H264_LEVEL_4_1',
            LookAheadRateControl: 'HIGH',
            ParControl: 'INITIALIZE_FROM_SOURCE',
            Profile: 'MAIN',
            RateControlMode: 'CBR',
            SceneChangeDetect: 'ENABLED',
            SpatialAq: 'ENABLED',
            Syntax: 'DEFAULT',
            TemporalAq: 'ENABLED',
          },
        },
        Height: 432,
        Name: 'video_768_432',
        ScalingBehavior: 'DEFAULT',
        Width: 768,
      },
      {
        CodecSettings: {
          H264Settings: {
            AdaptiveQuantization: 'HIGH',
            AfdSignaling: 'NONE',
            Bitrate: 2200000,
            ColorMetadata: 'INSERT',
            EntropyEncoding: 'CABAC',
            FlickerAq: 'ENABLED',
            ForceFieldPictures: 'DISABLED',
            FramerateControl: 'SPECIFIED',
            FramerateDenominator: 1001,
            FramerateNumerator: 30000,
            GopBReference: 'ENABLED',
            GopClosedCadence: 1,
            GopNumBFrames: 3,
            GopSize: 60,
            GopSizeUnits: 'FRAMES',
            Level: 'H264_LEVEL_4_1',
            LookAheadRateControl: 'HIGH',
            NumRefFrames: 1,
            ParControl: 'INITIALIZE_FROM_SOURCE',
            Profile: 'HIGH',
            RateControlMode: 'CBR',
            ScanType: 'PROGRESSIVE',
            SceneChangeDetect: 'ENABLED',
            SpatialAq: 'ENABLED',
            SubgopLength: 'FIXED',
            Syntax: 'DEFAULT',
            TemporalAq: 'ENABLED',
            TimecodeInsertion: 'DISABLED',
          },
        },
        Height: 540,
        Name: 'video_960_540',
        RespondToAfd: 'NONE',
        ScalingBehavior: 'DEFAULT',
        Sharpness: 50,
        Width: 960,
      },
      {
        CodecSettings: {
          H264Settings: {
            AdaptiveQuantization: 'HIGH',
            Bitrate: 3300000,
            ColorMetadata: 'INSERT',
            EntropyEncoding: 'CABAC',
            FlickerAq: 'ENABLED',
            FramerateControl: 'SPECIFIED',
            FramerateDenominator: 1001,
            FramerateNumerator: 30000,
            GopBReference: 'ENABLED',
            GopNumBFrames: 3,
            GopSize: 60,
            GopSizeUnits: 'FRAMES',
            Level: 'H264_LEVEL_4_1',
            LookAheadRateControl: 'HIGH',
            ParControl: 'INITIALIZE_FROM_SOURCE',
            Profile: 'HIGH',
            RateControlMode: 'CBR',
            SceneChangeDetect: 'ENABLED',
            SpatialAq: 'ENABLED',
            Syntax: 'DEFAULT',
            TemporalAq: 'ENABLED',
          },
        },
        Height: 720,
        Name: 'video_1280_720_1',
        ScalingBehavior: 'DEFAULT',
        Width: 1280,
      },
    ],
  },
  InputAttachments: [
    {
      InputAttachmentName: '1',
      InputId: '1642392',
      InputSettings: {
        AudioSelectors: [],
        CaptionSelectors: [],
        DeblockFilter: 'DISABLED',
        DenoiseFilter: 'DISABLED',
        FilterStrength: 1,
        InputFilter: 'AUTO',
        SourceEndBehavior: 'CONTINUE',
      },
    },
  ],
  InputSpecification: {
    Codec: 'AVC',
    MaximumBitrate: 'MAX_10_MBPS',
    Resolution: 'HD',
  },
  LogLevel: 'DISABLED',
  Name: user.id,
  RoleArn: 'arn:aws:iam::727441280422:role/MediaLiveAccessRole',
  Tags: {},
});
