apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: dgurney/corona-window-api:latest
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: production
            - name: DATABASE_HOST
              value: corona-window-staging.ctgvfpoeqoab.us-east-1.rds.amazonaws.com
            - name: DATABASE_PORT
              value: '5432'
            - name: DATABASE_USERNAME
              value: postgres
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password
                  key: DATABASE_PASSWORD
            - name: DATABASE_NAME
              value: postgres
            - name: WEB_ORIGIN
              value: 'http://localhost'
            - name: RTMP_ORIGIN
              value: rtmp://192.168.64.3
            - name: RTMP_PATH
              value: /rtmp/stream
            - name: COOKIE_SESSION_KEY
              valueFrom:
                secretKeyRef:
                  name: cookie-session-key
                  key: COOKIE_SESSION_KEY
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-access-key-id
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secret-access-key
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_S3_BUCKET
              value: corona-window-dev
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret-key
                  key: STRIPE_SECRET_KEY
      imagePullSecrets:
        - name: dgurney-docker-hub-credentials
