name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  update:
    name: Update production server
    runs-on: ubuntu-latest
    steps:
      - name: Run `start.production.sh` on production server
        uses: appleboy/ssh-action@master
        with:
          host: api.gigwindow.com
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION_SERVER }}
          script: cd gig-window && ./start.production.sh
