name: Deploy to Staging

on:
  pull_request:
    types: [opened, synchronize]

# on:
#   push:
#     branches:
#       - develop

jobs:
  build-push-update:
    name: Build images, push to Docker Hub, and update staging server
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Build `nginx` Docker image and push to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: dgurney/gig-window-nginx
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          workdir: nginx
          context: nginx
          tags: 'latest,${{ github.sha }}'

      # - name: Run `start.staging.sh` on staging server
      #   uses: garygrossgarten/github-action-ssh@release
      #   with:
      #     command: sh start.staging.sh
      #     host: api-staging.gigwindow.com
      #     username: root
      #     privateKey: ${{ secrets.PRIVATE_SSH_KEY }}
