name: Run tests on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test-web:
    name: Run unit tests for `web`
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node environment
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn test:ci
