name: Run tests on PR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node environment
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Switch to web directory
        run: cd web

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run unit tests
        run: yarn test:ci
